# Generated by Django 5.2.13 on 2026-04-30 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RequiredDocument",
            fields=[
                ("document_id", models.AutoField(primary_key=True, serialize=False)),
                ("document_name", models.CharField(max_length=140, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "applies_to_award_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MERIT", "Merit"),
                            ("NEED", "Need Based"),
                            ("ATHLETIC", "Athletic"),
                            ("OTHER", "Other"),
                        ],
                        help_text="Leave blank when the document can apply to any award type.",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["document_name"],
            },
        ),
        migrations.CreateModel(
            name="ActionItem",
            fields=[
                ("action_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("BALANCE", "Balance"),
                            ("DOCUMENT", "Document"),
                            ("PAYMENT", "Payment"),
                            ("AID", "Aid"),
                            ("GENERAL", "General"),
                        ],
                        default="GENERAL",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("NORMAL", "Normal"),
                            ("URGENT", "Urgent"),
                        ],
                        default="NORMAL",
                        max_length=20,
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("COMPLETED", "Completed"),
                            ("WAIVED", "Waived"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_items",
                        to="finance.student",
                    ),
                ),
            ],
            options={
                "ordering": ["status", "due_date", "-priority", "student__last_name"],
            },
        ),
        migrations.CreateModel(
            name="ApplicationDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REQUIRED", "Required"),
                            ("SUBMITTED", "Submitted"),
                            ("ACCEPTED", "Accepted"),
                            ("REJECTED", "Rejected"),
                            ("WAIVED", "Waived"),
                        ],
                        default="REQUIRED",
                        max_length=20,
                    ),
                ),
                ("received_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="finance.aidapplication",
                    ),
                ),
                (
                    "required_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="application_documents",
                        to="finance.requireddocument",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "application__student__last_name",
                    "required_document__document_name",
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("application", "required_document"),
                        name="unique_application_required_document",
                    )
                ],
            },
        ),
    ]
