# Generated by Django 5.2.13 on 2026-05-01 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_student_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FinanceDivision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "permissions": [
                    ("access_dashboard", "Can access staff dashboard"),
                    ("view_student_directory", "Can view student directory"),
                    ("manage_billing", "Can manage charges and payments"),
                    ("manage_aid", "Can manage aid applications"),
                    ("manage_action_items", "Can manage action items"),
                    ("view_reports", "Can view reports"),
                    ("view_audit_log", "Can view audit log"),
                    ("full_supervision", "Finance supervisor override"),
                    ("system_admin", "Finance system administrator"),
                ],
                "default_permissions": (),
                "verbose_name_plural": "Finance divisions",
            },
        ),
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                ("batch_id", models.AutoField(primary_key=True, serialize=False)),
                ("label", models.CharField(blank=True, max_length=160)),
                ("source_system", models.CharField(max_length=80)),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-imported_at"],
            },
        ),
        migrations.AddField(
            model_name="actionitem",
            name="imported_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="actionitem",
            name="source_system",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="aidapplication",
            name="imported_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="aidapplication",
            name="source_system",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="applicationdocument",
            name="imported_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="applicationdocument",
            name="source_system",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="payment",
            name="imported_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="source_system",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="student",
            name="imported_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="source_system",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="studentcharge",
            name="imported_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentcharge",
            name="source_system",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("VIEW", "View"),
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                            ("DIRECTORY", "Directory"),
                        ],
                        max_length=20,
                    ),
                ),
                ("object_type", models.CharField(max_length=120)),
                ("object_id", models.CharField(blank=True, max_length=80)),
                ("summary", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="finance_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="finance_audit_logs",
                        to="finance.student",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="actionitem",
            name="import_batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="action_items",
                to="finance.importbatch",
            ),
        ),
        migrations.AddField(
            model_name="aidapplication",
            name="import_batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="aid_applications",
                to="finance.importbatch",
            ),
        ),
        migrations.AddField(
            model_name="applicationdocument",
            name="import_batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="application_documents",
                to="finance.importbatch",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="import_batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="finance.importbatch",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="import_batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="finance.importbatch",
            ),
        ),
        migrations.AddField(
            model_name="studentcharge",
            name="import_batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="charges",
                to="finance.importbatch",
            ),
        ),
    ]

